import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'cs' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Simple dictionary for translations
const translations: Record<Language, Record<string, string>> = {
  cs: {
    'nav.dashboard': 'Dashboard',
    'nav.skills': 'Dovednosti',
    'nav.social': 'Social Club',
    'nav.leaderboard': 'Žebříček',
    'nav.quests': 'Questy',
    'nav.learning': 'Vzdělávání',
    'nav.manager': 'Manažer',
    'nav.approvals': 'Schvalování',
    'header.search': 'Hledat dovednosti, lidi nebo kurzy...',
    'header.employee': 'Zaměstnanec',
    'header.manager': 'Manažer',
    'header.level': 'Úroveň',
    'dashboard.welcome': 'Vítej zpět',
    'dashboard.tempo': 'Tento týden válíš! Udrž si tohle tempo.',
    'dashboard.current_level': 'Aktuální Úroveň',
    'dashboard.xp_to_next': 'XP do Úrovně',
    'dashboard.streak': 'Řada dní',
    'dashboard.days': 'dní',
    'dashboard.badges_kudos': 'Odznaky & Kudos',
    'dashboard.earned_kudos': 'Získaná Kudos',
    'dashboard.badges': 'Odznaky',
    'dashboard.view_hall_of_fame': 'Zobrazit síň slávy',
    'dashboard.active_quests': 'Aktivní Úkoly (Questy)',
    'dashboard.view_all': 'Zobrazit vše',
    'dashboard.done': 'Hotovo',
    'dashboard.recommended': 'Doporučeno pro tebe',
    'dashboard.based_on_gaps': 'Na základě dovednostních mezer',
    'dashboard.match': 'Shoda',
    'dashboard.start_learning': 'Začít studovat',
    'dashboard.skill_profile': 'Profil Dovedností',
    'dashboard.strong_in': 'Jsi silný v',
    'dashboard.hard_skills': 'Tvrdých dovednostech',
    'dashboard.focus_on_leadership': 'Zkus se zaměřit na Leadership pro vyvážení profilu.',
    'dashboard.view_matrix': 'Zobrazit detailní matici',
    'dashboard.social_club_desc': 'Propoj se s kolegy, najdi mentory, nebo se jím staň!',
    'dashboard.join_discussion': 'Zapojit se do diskuze',
    'skills.title': 'Matice Dovedností',
    'skills.subtitle': 'Spravuj své expertízy a ověřuj svůj růst.',
    'skills.add': 'Přidat dovednost',
    'skills.approved': 'Schválené dovednosti',
    'skills.approved_desc': 'Ověřeno kolegy a manažery',
    'skills.self_rated': 'Vlastní hodnocení',
    'skills.self_rated_desc': 'Viditelné pouze tobě, dokud není schváleno',
    'skills.request_approval': 'Požádat o schválení',
    'skills.gap_detected': 'Detekována mezera',
    'skills.gap_desc': 'Tvoje role Produktový Designér obvykle vyžaduje úroveň 60. Momentálně jsi na úrovni 40.',
    'skills.view_course': 'Zobrazit doporučený kurz',
    'skills.find_mentor': 'Najít mentora',
    'skills.modal_title': 'Přidat novou dovednost',
    'skills.skill_name': 'Název dovednosti',
    'skills.category': 'Kategorie',
    'skills.hard': 'Tvrdé dovednosti',
    'skills.soft': 'Měkké dovednosti',
    'skills.save': 'Uložit dovednost',
    'skills.level': 'Úroveň',
    'social.title': 'Social Club',
    'social.subtitle': 'Propoj se s kolegy, najdi mentory, nebo se jím staň!',
    'social.join': 'Zapojit se do diskuze',
    'social.share_placeholder': 'Sdílej úspěch, poděkuj nebo požádej o radu...',
    'social.post': 'Přispět',
    'social.add_tag': 'Přidat štítek',
    'social.give_badge': 'Dát odznak',
    'social.coffee_skill': 'Kafe & Skill',
    'social.help_request': 'Hledá pomoc',
    'social.help_offer': 'Nabízí pomoc',
    'social.add_challenge': '+ Přidat vlastní výzvu',
    'social.find_expert': 'Najít Experta',
    'social.find_expert_desc': 'Hledej kolegy, kteří tě mohou mentorovat.',
    'social.find_expert_placeholder': "např., 'Python' nebo 'Vyjednávání'",
    'social.top_contributors': 'Nejlepší přispěvatelé',
    'social.message': 'Zpráva',
    'leaderboard.title': 'Síň slávy',
    'leaderboard.subtitle': 'Nejlepší z nejlepších v tomto měsíci.',
    'leaderboard.subtitle_desc': 'Nejlepší hráči ve SkillVerse. Jsi mezi nimi?',
    'leaderboard.total_xp': 'Celkové XP',
    'leaderboard.hard_skills': 'Hard Skills',
    'leaderboard.soft_skills': 'Soft Skills',
    'learning.title': 'Vzdělávací Katalog',
    'learning.subtitle': 'Rozvíjej své dovednosti s kurzy na míru.',
    'learning.filter': 'Filtrovat',
    'learning.match': 'Shoda',
    'learning.enroll': 'Zapsat se',
    'quests.title': 'Tvé Úkoly (Questy)',
    'quests.subtitle': 'Plň výzvy, získávej XP a posouvej svou kariéru.',
    'quests.active': 'Právě probíhá',
    'quests.progress': 'Průběh',
    'quests.continue': 'Pokračovat',
    'quests.available': 'Dostupné výzvy',
    'quests.accept': 'Přijmout výzvu',
    'quests.completed': 'Dokončeno',
    'quests.earned': 'Získáno',
    'manager.title': 'Přehled Týmu',
    'manager.subtitle': 'Sleduj rozvoj dovedností a spravuj schvalování.',
    'manager.download_report': 'Stáhnout report',
    'manager.assign_training': 'Přiřadit školení',
    'manager.skill_gap': 'Dovednostní mezera týmu',
    'manager.improvement': 'Zlepšení o',
    'manager.completed_courses': 'Dokončené kurzy',
    'manager.this_quarter': 'Tento kvartál',
    'manager.active_students': 'Aktivní studenti',
    'manager.high_engagement': 'Vysoká angažovanost',
    'manager.pending_approvals': 'Čekající schválení',
    'manager.check': 'Zkontrolovat',
    'manager.team_members': 'Členové týmu',
    'manager.search': 'Hledat...',
    'manager.employee': 'Zaměstnanec',
    'manager.role': 'Role',
    'manager.gap': 'Mezera',
    'manager.status': 'Stav',
    'manager.action': 'Akce',
    'manager.pending': 'Čeká',
    'manager.ok': 'V pořádku',
    'manager.learning_activity': 'Aktivita ve vzdělávání',
    'manager.assigned': 'Přiřazeno',
    'manager.completed': 'Dokončeno',
    'manager.requires_attention': 'Vyžaduje pozornost',
    'manager.attention_desc': 'Zaměstnanci, kteří se nepřihlásili 3+ dny',
    'manager.last_seen': 'Naposledy viděn před',
    'manager.nudge': 'Popostrčit',
    'approvals.title': 'Schvalování Dovedností',
    'approvals.subtitle': 'Ověř, zda členové tvého týmu skutečně dosáhli deklarované úrovně.',
    'approvals.empty_title': 'Vše hotovo!',
    'approvals.empty_desc': 'Nemáš žádné čekající žádosti o schválení.',
    'approvals.request_text': 'Žádá o schválení',
    'approvals.at_level': 'na úrovni',
    'approvals.approve': 'Schválit',
    'approvals.reject': 'Zamítnout',
  },
  en: {
    'nav.dashboard': 'Dashboard',
    'nav.skills': 'Skills',
    'nav.social': 'Social Club',
    'nav.leaderboard': 'Leaderboard',
    'nav.quests': 'Quests',
    'nav.learning': 'Learning',
    'nav.manager': 'Manager',
    'nav.approvals': 'Approvals',
    'header.search': 'Search skills, people or courses...',
    'header.employee': 'Employee',
    'header.manager': 'Manager',
    'header.level': 'Level',
    'dashboard.welcome': 'Welcome back',
    'dashboard.tempo': "You're rocking it this week! Keep up the pace.",
    'dashboard.current_level': 'Current Level',
    'dashboard.xp_to_next': 'XP to Level',
    'dashboard.streak': 'Day Streak',
    'dashboard.days': 'days',
    'dashboard.badges_kudos': 'Badges & Kudos',
    'dashboard.earned_kudos': 'Kudos Earned',
    'dashboard.badges': 'Badges',
    'dashboard.view_hall_of_fame': 'View Hall of Fame',
    'dashboard.active_quests': 'Active Quests',
    'dashboard.view_all': 'View All',
    'dashboard.done': 'Done',
    'dashboard.recommended': 'Recommended for you',
    'dashboard.based_on_gaps': 'Based on skill gaps',
    'dashboard.match': 'Match',
    'dashboard.start_learning': 'Start Learning',
    'dashboard.skill_profile': 'Skill Profile',
    'dashboard.strong_in': "You're strong in",
    'dashboard.hard_skills': 'Hard Skills',
    'dashboard.focus_on_leadership': 'Try focusing on Leadership to balance your profile.',
    'dashboard.view_matrix': 'View detailed matrix',
    'dashboard.social_club_desc': 'Connect with colleagues, find mentors, or become one!',
    'dashboard.join_discussion': 'Join the discussion',
    'skills.title': 'Skill Matrix',
    'skills.subtitle': 'Manage your expertise and verify your growth.',
    'skills.add': 'Add Skill',
    'skills.approved': 'Approved Skills',
    'skills.approved_desc': 'Verified by peers and managers',
    'skills.self_rated': 'Self-rated',
    'skills.self_rated_desc': 'Visible only to you until approved',
    'skills.request_approval': 'Request approval',
    'skills.gap_detected': 'Gap detected',
    'skills.gap_desc': 'Your role Product Designer usually requires level 60. You are currently at level 40.',
    'skills.view_course': 'View recommended course',
    'skills.find_mentor': 'Find a mentor',
    'skills.modal_title': 'Add new skill',
    'skills.skill_name': 'Skill name',
    'skills.category': 'Category',
    'skills.hard': 'Hard Skills',
    'skills.soft': 'Soft Skills',
    'skills.save': 'Save Skill',
    'skills.level': 'Level',
    'social.title': 'Social Club',
    'social.subtitle': 'Connect with colleagues, find mentors, or become one!',
    'social.join': 'Join the discussion',
    'social.share_placeholder': 'Share success, thank someone or ask for advice...',
    'social.post': 'Post',
    'social.add_tag': 'Add tag',
    'social.give_badge': 'Give badge',
    'social.coffee_skill': 'Coffee & Skill',
    'social.help_request': 'Looking for help',
    'social.help_offer': 'Offering help',
    'social.add_challenge': '+ Add your own challenge',
    'social.find_expert': 'Find an Expert',
    'social.find_expert_desc': 'Search for colleagues who can mentor you.',
    'social.find_expert_placeholder': "e.g., 'Python' or 'Negotiation'",
    'social.top_contributors': 'Top contributors',
    'social.message': 'Message',
    'leaderboard.title': 'Hall of Fame',
    'leaderboard.subtitle': 'The best of the best this month.',
    'leaderboard.subtitle_desc': 'The best players in SkillVerse. Are you among them?',
    'leaderboard.total_xp': 'Total XP',
    'leaderboard.hard_skills': 'Hard Skills',
    'leaderboard.soft_skills': 'Soft Skills',
    'learning.title': 'Learning Catalog',
    'learning.subtitle': 'Develop your skills with tailored courses.',
    'learning.filter': 'Filter',
    'learning.match': 'Match',
    'learning.enroll': 'Enroll',
    'quests.title': 'Your Quests',
    'quests.subtitle': 'Complete challenges, earn XP and advance your career.',
    'quests.active': 'In Progress',
    'quests.progress': 'Progress',
    'quests.continue': 'Continue',
    'quests.available': 'Available Challenges',
    'quests.accept': 'Accept Challenge',
    'quests.completed': 'Completed',
    'quests.earned': 'Earned',
    'manager.title': 'Team Overview',
    'manager.subtitle': 'Track skill development and manage approvals.',
    'manager.download_report': 'Download report',
    'manager.assign_training': 'Assign training',
    'manager.skill_gap': 'Team skill gap',
    'manager.improvement': 'Improvement by',
    'manager.completed_courses': 'Completed courses',
    'manager.this_quarter': 'This quarter',
    'manager.active_students': 'Active students',
    'manager.high_engagement': 'High engagement',
    'manager.pending_approvals': 'Pending approvals',
    'manager.check': 'Check',
    'manager.team_members': 'Team members',
    'manager.search': 'Search...',
    'manager.employee': 'Employee',
    'manager.role': 'Role',
    'manager.gap': 'Gap',
    'manager.status': 'Status',
    'manager.action': 'Action',
    'manager.pending': 'Pending',
    'manager.ok': 'OK',
    'manager.learning_activity': 'Learning activity',
    'manager.assigned': 'Assigned',
    'manager.completed': 'Completed',
    'manager.requires_attention': 'Requires attention',
    'manager.attention_desc': "Employees who haven't logged in for 3+ days",
    'manager.last_seen': 'Last seen',
    'manager.nudge': 'Nudge',
    'approvals.title': 'Skill Approvals',
    'approvals.subtitle': 'Verify if your team members have actually reached the declared level.',
    'approvals.empty_title': 'All done!',
    'approvals.empty_desc': 'You have no pending approval requests.',
    'approvals.request_text': 'Requests approval of',
    'approvals.at_level': 'at level',
    'approvals.approve': 'Approve',
    'approvals.reject': 'Reject',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('cs');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
